import { notFound } from "next/navigation";
import { getPage } from "@/lib/graphql";
import { ensureH1, sanitizeHtml } from "@/lib/sanitize";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

// Legal copy is maintained in WordPress (generated by Termly), which supplies its own
// title and "last updated" line, so this renders the body only. Termly sets some
// titles as an h3, so ensureH1 promotes the first heading to give the page an h1.
export async function LegalPage({ slug }: { slug: string }) {
  const page = await getPage(slug);
  if (!page) notFound();

  return (
    <>
      <Header />
      <main className="pt-16 min-h-screen bg-white">
        <article className="max-w-3xl mx-auto px-4 py-20">
          <div className="legal-content" dangerouslySetInnerHTML={{ __html: ensureH1(sanitizeHtml(page.content)) }} />
        </article>
      </main>
      <Footer />
    </>
  );
}
